[package]
name = "str0m"
version = "0.1.0"
authors = ["Martin Algesten <martin@algesten.se>"]
edition = "2018"

[profile.dev]
panic = "abort"
[profile.release]
panic = "abort"

[dependencies]
combine = "4"
crc = "1"
futures = "0.3"
hmac = "0.10"
hreq = "0.8"
log = "0.4"
openssl = { version = "0.10", features = ["vendored"] }
openssl-sys = "^0.9"
pnet = "0.27"
pretty_env_logger = "0.4"
rand = "0.8"
rustls = "0.19"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha-1 = "0.9"
tokio = { version = "1", features = ['rt-multi-thread', 'macros', 'net', 'sync', 'time'] }
