[package]
name = "str0m"
version = "0.1.0"
authors = ["Martin Algesten <martin@algesten.se>"]
edition = "2018"

[profile.dev]
panic = "abort"
[profile.release]
panic = "abort"

[dependencies]
tracing = "0.1"
combine = "4"
once_cell = "1"

# slab = "0.4"
# crossbeam-queue = "0.3"
# dashmap = "5"

hmac = "0.11"
sha-1 = "0.9"
rand = "0.8"
crc = "2"

# Sadly no DTLS support in rustls.
openssl = { version = "0.10", features = ["vendored"] }
openssl-sys = "^0.9"

[dev-dependencies]
tracing-subscriber = "0.2"
