[package]
name = "sdp"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1"
tracing = "0.1"
serde = "1"

combine = "4"

dtls = { path = "../dtls" }
ice = { path = "../ice" }
rtp = { path = "../rtp" }
